#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Aug 23 08:26:52 AEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.8.1 + EuphoriaPatches_1.9.3
