name = "Create Aeronautics Physics Server"
author = "WildFire"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07578793e6789f81f373c54885b129587795153511874943c79aa0d34e5a2fc7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
