name = "Create Aeronautics Physics Server"
author = "WildFire"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2446a3cd8a8b045dbabd5475c43a0e3ccfc77c821d691e2ca7fd2ed2a3d303e5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
