name = "Create Aeronautics Physics Server"
author = "WildFire"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75c24a0d834f60fde70bfe675244e37c00fb9094680b979cf467304718fa2d89"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
